### ISSUE TITLE
Autoscaling broken?

### ISSUE THREAD

**Issue by spencerhakim** [convox/rack#2036]
When I deploy one of my apps, Convox usually temporarily autoscales up to accommodate the extra containers, but this seems to have stopped working within the last few updates. CloudFormation doesn't even register any updates for the stack. Not sure which Lambda function (if any) is responsible for updating the autoscaling group, so I don't know which logs to look at in CloudWatch.

Convox messages in Slack (sent once every 60 seconds or so):
<img width="264" alt="capturfiles-20170368_130368" src="https://cloud.githubusercontent.com/assets/606857/23765240/8c2e19de-04ce-11e7-990e-5f0dd9f3241c.png">

Encountered this with both the latest 20170309001137 and the previous 20170306140228. When I last deployed this app on March 3rd it worked fine, and I'm guessing I was running 20170301205054.

**Comment by soulshake** [comment]
@spencerhakim thanks for the report. We're working on a fix now.

**Comment by frankleng** [comment]
@spencerhakim are you using a custom AMI? can u check the "Activity History" in your Autoscaling group? 

want to find out if you are running into the same issue we did.

**Comment by spencerhakim** [comment]
Definitely not using a custom AMI, I try to keep things as stock as possible. The only activity listed is from when I manually adjusted the instance count through the Convox web app after I noticed it wasn't adjusting on its own.

**Comment by blackdynamo** [comment]
I think I am having issues with the deploy process as well. Not sure if it's specific to the auto scaling or not. I rebuilt my rack, deployed and things are fine. I then deployed again and it gets back into the container cycling state and seems to be stuck in updating status.

![image](https://cloud.githubusercontent.com/assets/245688/23773719/c563d9a0-04dd-11e7-95ed-0224ca3f936c.png)
![image](https://cloud.githubusercontent.com/assets/245688/23773741/e09280fa-04dd-11e7-968d-4012c0ac4a47.png)
![image](https://cloud.githubusercontent.com/assets/245688/23773701/ae8615ae-04dd-11e7-8bac-4f6facdd56e8.png)
![image](https://cloud.githubusercontent.com/assets/245688/23773801/12e53bec-04de-11e7-8178-025b391864d4.png)

**Comment by soulshake** [comment]
@spencerhakim @frankleng @blackdynamo 
We've just issued a release that should fix the problem. Let us know if that doesn't help.

**Comment by frankleng** [comment]
@soulshake I'm experiencing a different problem. The autoscaler fails because it's trying to set `encrypt` flag on an EBS volume with a snapshot attached. We run a custom AMI built by `packer`.

in EC2 logs we get
```
the encrypted flag cannot be specified since device /dev/xvdcz has a snapshot specified. Launching EC2 instance failed.
```

**Comment by soulshake** [comment]
@MiguelMoll any ideas about this?

**Comment by MiguelMoll** [comment]
There was a recent change to the launch control figuration where the volumes are encrypted by default. Unfortunately, AWS doesn't support encryption from unencrypted snapshots. The easiest option would be to re-create the AMI with encryption enabled.

This is indeed an unrelated issue. We should document this as expected behavior for future reference.

**Comment by frankleng** [comment]
@soulshake @MiguelMoll making an encrypted snapshots didn't fix it either.
I think it's trying to set the `encrypt` flag even if the device is already encrypted.

Possible to make setting the flag conditional?

**Comment by mattmanning** [comment]
@frankleng We have a change coming here https://github.com/convox/rack/pull/2068 that should help you get around this when it's released.
